# Generated by Django 4.0.1 on 2023-04-05 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserType',
            new_name='CustomerType',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=255)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customertype')),
            ],
        ),
    ]
