# Generated by Django 4.0.1 on 2023-04-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_author_exemplary_exemplarytype_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=7),
        ),
        migrations.AlterField(
            model_name='exemplary',
            name='exemplary_type',
            field=models.CharField(choices=[('book', 'Book'), ('newspaper', 'Newspaper'), ('magazine', 'Magazine')], default='book', max_length=10),
        ),
        migrations.DeleteModel(
            name='CustomerType',
        ),
        migrations.DeleteModel(
            name='ExemplaryType',
        ),
    ]
