# Generated by Django 4.0.1 on 2023-04-06 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customer_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('book', 'Book'), ('newspaper', 'Newspaper'), ('magazine', 'Magazine')], default='book', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
        ),
        migrations.RemoveField(
            model_name='exemplary',
            name='author',
        ),
        migrations.RemoveField(
            model_name='exemplary',
            name='exemplary_type',
        ),
        migrations.RemoveField(
            model_name='exemplary',
            name='title',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='exemplary',
        ),
        migrations.AddField(
            model_name='exemplary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ExemplaryAvailables',
        ),
        migrations.AddField(
            model_name='exemplary',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.work'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.work'),
        ),
    ]
